### ISSUE TITLE
Ferns not listed in the 'Day Trader' advancement

### ISSUE THREAD

**Issue by saltynuggets0** [jsorrell/CarpetSkyAdditions#101]
Ferns can only be obtained in skyblock from the Wandering Trader, as using bone meal on grass only generates ferns in Bedrock Edition.

However, the 'Day Trader' advancement does not include ferns in the list of items needed to obtain it.

Solutions to fix:
- add Ferns to the list of items required for the advancement, bumping up the number of items needed to 26
- make the usage of bone meal on grass able to generate Ferns, as parity with Bedrock Edition
  (this could be made biome dependent as to give an extra challenge)

**Comment by jsorrell** [comment]
Still unfixed for the Acacia datapack.
