### ISSUE TITLE
Mod crashes when you start: code (1)

### ISSUE THREAD

**Issue by Loweredgames** [jsorrell/CarpetSkyAdditions#106]
Mods used:
- DistantHorizons-1.6.11a-1.19.4
- lithium-fabric-mc1.19.4-0.11.1
- sodium-fabric-mc1.19.4-0.4.10+build.24
- modmenu-6.1.0-rc.4

---
- fabric-carpet-1.19.4-1.4.101+v230319.jar
- carpetskyadditions-1.19.4-4.3.0.jar
- cloth-config-10.0.96-fabric.jar
- fabric-api-0.76.0+1.19.4.jar
---

Log:
[latest.log](https://github.com/jsorrell/CarpetSkyAdditions/files/11022828/latest.log)

**Comment by jsorrell** [comment]
Thanks for reporting this. I've identified the issue and a working version should be out within the hour.

**Comment by Loweredgames** [comment]
ok

**Comment by Loweredgames** [comment]
it works, so I close the problem
