### ISSUE TITLE
only one data pack

### ISSUE THREAD

**Issue by arcZERO33** [jsorrell/CarpetSkyAdditions#107]
I started the world with only acacia data pack, is it possible to add another data pack to this world? Because there is no way to get lava, I got over 1000 gifts and nothing. please help.

**Comment by jsorrell** [comment]
You can enable the datapack by running the command

`/datapack enable "carpetskyadditions/skyblock" before "carpetskyadditions/skyblock_acacia"`

In singleplayer without cheats, you need to open to lan in order to temporarily enable commands.

**Comment by razgriz5000** [comment]
For reference, does the order in the datapack selection screen determine which is loaded first?  
![image](https://user-images.githubusercontent.com/10761855/226477952-aed86ef9-fab4-4e3a-9ac0-73b904c8615b.png)

**Comment by arcZERO33** [comment]
the command only worked on /datapack enable "carpetskyadditions/skyblock" after "carpetskyadditions/skyblock_acacia"
she didn't want to activate on /datapack enable "carpetskyadditions/skyblock" before "carpetskyadditions/skyblock_acacia"
could it be a problem for my world?
When i entered your command it threw me out: Unknown datapack carpetskyadditions/skyblock 
dont know whay

**Comment by arcZERO33** [comment]
ok tnx allot its working now
