### ISSUE TITLE
Obtaining 1.20 Mobs & Items

### ISSUE THREAD

**Issue by Kluski42** [jsorrell/CarpetSkyAdditions#108]
Looking at the new Trails and Tales update features, I was interested in how you planned to include them into Skyblock. The currently unobtainable mobs and items, as well as some information and thoughts on them are:

- Sniffers
   - Their eggs are normally found in suspicious sand located in Warm Ocean Ruins.
   - ~~Adding them could provide an alternative source for the first moss block, being more reliable than waiting for a wandering trader to trade one.~~ (Edit: this feature was removed)
- Camels
   - Normally they spawn in desert villages upon generation.
   - As a suggestion, perhaps they could spawn on sand / red sand in villages in desert biomes, similar to cats.
- Armor Trims
   - They are usually found in loot chests in structures and in suspicious sand / gravel.
- Netherite Upgrade Smithing Template
   - Usually obtained through loot chests in bastions.
   - Required in order to upgrade diamond gear into netherite gear. That means this is just as important as the netherrite ingot.
   - I think this and netherite should be obtained in different ways. Perhaps bartering, or having a piglin brute kill an iron golem?
- Pottery Shards
   - Found in suspicious sand or gravel, with the type dependent on the structure it's found in.

It's notable that many of the features that are currently unobtainable are so as a result of the lack of suspicious sand / gravel in structures. Some ideas on how this can be circumvented are:
- Giving the player a method to create sussy sand and gravel inside of the bounding box of a structure. In addition, this would populate the sand with the items found in the structure.
- Sniffer loot tables can get merged with the sus block loot tables when digging in structures. Meaning it could, for example, obtain torchflower seeds or pottery shards in a desert pyramid bounding box.
   - It should be noted that sniffers are originally obtained from suspicious sand in warm ocean ruins, meaning there needs to be another way to get them.

**Comment by Malachi-lewis** [comment]
I would vote for the first option to obtain sus sand, as this mod also has the goal of making every block obtainable. It is also likely that they will introduce an achievement for finding sus sand(this mod also makes a point to keep all achievements available).

**Comment by Kluski42** [comment]
@Malachi-lewis Good point on the advancement, I agree that it seems likely that Mojang would add an advancement requiring suspicious sand / gravel. Thanks for the feedback!

**Comment by jsorrell** [comment]
My thoughts on this so far:
- Camels
  - A camel could replace the trader llamas when a wandering trader spawns in a desert (maybe savanna too?). This would match the historical use of them as pack animals.
- Suspicious Sand/Gravel
  - Suspicious sand/gravel is currently obtainable as an item in vanilla for example by dropping it in a bubble column and waiting until it breaks. If this mod wants to allow people to obtain everything available in vanilla, sus sand/gravel has to exist somehow.
  - The idea of suspicious sand/gravel is that they contain the leftovers of ancient civilizations, which isn't really something that is compatible with a skyblock world b/c nothing is leftover. So to get it the lore has to be broken a bit.
  - Maybe the best way to do this would be magic? Maybe dragons breath could convert sand/gravel into the suspicious version? Maybe dropping sand/gravel onto something magical?
  - Sus sand/gravel is very limited in vanilla worlds (and finite) so it should be difficult to farm/obtain via this mod.
  - I prefer the idea of converting the block or falling block entity into the suspicious version than the item b/c this will mean that the item versions are only obtained the way you do in vanilla and if this is patched in vanilla, it's patched here.
  - If a suspicious block is created in a position, this mod can make it have the same loot table as it would if it naturally generated there. For example, sand converted into suspicious sand within the boundaries of a desert pyramid can have the loot table of suspicious sand that would generate there.
  - Access to suspicious sand/gravel gives access to many of the new items in 1.20 including:
    - Pottery shards
    - Sniffer Eggs -> Sniffers -> Torchflower and pitcher plant
    - Host, Raiser, Shaper and Wayfinder Armor Trim Templates
- Smithing Templates
  - The Tide Armor Trim Template is obtainable by killing Elder Guardians and is thus already obtainable.
  - These were created to encourage exploration and thus were tailor-made to be skyblock incompatible.
  - Only one is needed, and then they are reproducible.
  - They are all tied to certain structures and this mod should probably try to keep that tie as much as possible. They are also tied to specific blocks in their duplication recipe.
  - They could potentially be given a reward for completing certain advancements. Maybe people can trim their armor to show off their completion of difficult advancements?
  - Maybe doing something in their respective structures or with their respective blocks should give them?
- Netherite Upgrade Smithing Template
  - I agree that the current Netherrite/Ancient Debris method needs to be overhauled and that will likely come in the 1.20 version of this mod. The current method may fit the lore of Netherrite, but it's pretty boring and easy to farm currently.
  - Ancient debris, like sus sand/gravel, is the remains of an ancient civilization, so maybe it can be obtained similarly.
  - Only one template is needed, and then it is reproducible. However, the option should probably exist to get more in case the last is accidentally used, which rules out getting it as an advancement reward.
  - It should probably be bastion tied, somehow.
  - In vanilla, it generates in the same places as the snout armor trim smithing template, but is more common, especially in treasure bastion remnants.

**Comment by Kluski42** [comment]
>     * Camels
>       
>       * A camel could replace the trader llamas when a wandering trader spawns in a desert (maybe savanna too?). This would match the historical use of them as pack animals.

That's a neat idea. Perhaps wandering traders could ride the camels they spawn in with?
A potential problem with this variation however is the despawning: if they do despawn, getting a pair of permanent camels would be annoying. If they don't despawn, then eventually you'll have builds in deserts covered with camels.

>   * Suspicious Sand/Gravel 
> ............
> Maybe the best way to do this would be magic? Maybe dragons breath could convert sand/gravel into the suspicious version? Maybe dropping sand/gravel onto something magical?

Use suspicious stew to convert sand and gravel into their suspicious versions.
Jokes aside, I like the idea of dropping sand / gravel onto a end crystal to convert it to its suspicious variant. From a lore perspective:
- The ghast tear is associated with healing / restoration (regen potions and the crystal's regen beam)
- The eye of ender is associated with seeking (finding stronghold) and with transportation (portal activation and ender pearl as a component)
- Together, the eye is used to find out how it should / could be or it looks into ancient times copying a piece of what it sees, while the ghast tear could restore what the eye found into our world.
It's a bit of a stretch, but I think it works with enough mental gymnastics. From a gameplay perspective, you need 3+ farms (sand/gravel, sand/glass, blaze powder, and ender pearl) before being able to renewably generate suspicious blocks, and requiring some manual labor (crafting components, restocking on materials, placing end crystal, placing sand/gravel, and using the brush).

**Comment by jsorrell** [comment]
In the test I implemented for camels, I made it so the camel despawns in the same way as a trader llama. Like trader llamas, despawning can be prevented by riding the camel or leashing it. They can't be tamed, so I made it so they remember if they've ever been saddled, and if they have, they never despawn.

A possible problem with a trader riding them is that the camel doesn't care about the trader when it walks around, so eventually it would likely suffocate the trader. But vanilla does this with spider jockeys/ravager riders already and traders always spawn on the highest block so, this would probably be OK. A camel farm could possibly be built by instantly freezing/suffocating the trader sitting on top with water or powdered snow. I'll try implementing this version and see which I like more.

**Comment by Kluski42** [comment]
> They can't be tamed, so I made it so they remember if they've ever been saddled, and if they have, they never despawn.

Smart solution, I like it, that would probably work. I haven't seen your code, so I don't know it's a problem or not, but in your position, I'd make the camels persistent after having a nametag used on them. Trader llamas despawn even if renamed if I remember correctly, so that's something to consider.
