### ISSUE TITLE
Is it possible to have any possible wood type for the advancements?

### ISSUE THREAD

**Issue by TreeOfSelf** [jsorrell/CarpetSkyAdditions#109]
Hi I know #64 mentioned other tree starts, but I have a server that selects a tree for your personal island based on the biome you in.

Is it even possible to have the advancements for the wood check for multiple types, or I am guessing that is not possible? Thanks.

**Comment by jsorrell** [comment]
That's definitely possible for the initial oak log/oak sapling advancements.

But starting with a tree that gives apples gives a different progression line to starting with those that don't. The advancements may not match what some players have to do to get golden apples.

**Comment by TreeOfSelf** [comment]
true on my server players can work with each other to get different wood types, I was mainly wondering if I could get it so the initial oak sapling/ oak trap door allow any wood if possible. Is that something I could do on my end with configuration?

**Comment by jsorrell** [comment]
This data pack should do what you want. It allows any log for the log advancement, any sapling for the sapling advancement, any wooden trapdoor for the trapdoor advancement, and requires all saplings for the Arborist and Day Trader advancements. Make sure it is enabled after the SkyBlock datapack to ensure it overrides the advancements in that.

[any_wood_datapack.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/11133247/any_wood_datapack.zip)

**Comment by TreeOfSelf** [comment]
Wow, thank you so much! Appreciate it.
