### ISSUE TITLE
suggestion to add goat ramming a quartz block giving 4 quartz pieces

### ISSUE THREAD

**Issue by h3oCharles** [jsorrell/CarpetSkyAdditions#11]
quartz blocks can be acquired from master-level masons, this can be an alternative way of getting quartz

**Comment by jsorrell** [comment]
Since nether quartz ore can be created and mined pre-Nether with quartz blocks and netherrack (from 9x rotten flesh) in a smithing table, there is already an alternative way of getting quartz. I'm not sure another is needed seeing as a bartering farm already gives all the quartz one would need.
