### ISSUE TITLE
Ideas for how to make 1.20 items (and netherite gear post-update) renewable

### ISSUE THREAD

**Issue by Godly000** [jsorrell/CarpetSkyAdditions#118]
A lot of the newer items have to be discovered through exploration, whether opening structure loot chests or brushing through suspicious sand/gravel. In skyblock however, none of these things generate. We can solve this problem and make these items renewable by giving Sniffers the ability to dig up sand and gravel, and when they do so, they will convert the block into its suspicious form. If the sniffer is also in a structure in which u can find armor trims (for example, end cities, jungle temples, desert temples, fortresses, etc.) then the suspicious block will also have a chance to contain that armor trim when dug up, although not guaranteed. As for obtaining the first Sniffer in a new world, we could replace the Copper drop of baby Drowned with a Sniffer Egg.

**Comment by Kluski42** [comment]
I don't know if you saw this yet, but I made a thread on the same topic before: https://github.com/jsorrell/CarpetSkyAdditions/issues/108.

As for your idea, I like it. I don't see why only baby drowned should have access to sniffer eggs though. I think any drowned can spawn with the eggs just like how they can spawn with shells. If you want to take advantage of the rarity the baby drowned provides, you can just make fewer drowned spawn with the egg.

**Comment by Godly000** [comment]
Yes, they could definitely hold them in place of nautlius shells. I was thinking that they would be a rare mob drop and replace copper, which means only baby Drowned can hold the eggs otherwise Copper wouldn't be renewable.
