### ISSUE TITLE
Piglin brute don't drop ancient debris

### ISSUE THREAD

**Issue by estouneide** [jsorrell/CarpetSkyAdditions#119]
I'm playing the mod, i tested a little farm, but any piglin brute drop ancient debris. Even with a looting III sword, i tested for hours, but i just got golden axes. I tried to found the datapack, but nothing appears on that list. I don't know if was removed from the mod, but its impossible to activate on game.

**Comment by jsorrell** [comment]
With the datapack enabled, they drop ancient debris. You must have the datapack disabled. It is embedded in the mod so it should show up in the datapacks list.

**Comment by jsorrell** [comment]
The datapack `carpetskyadditions:skyblock` should show up with the `/datapack list` command.

`/datapack enable "carpetskyadditions:skyblock"` should enable it.

If it's not there, you're using a very old version of this mod or something weird is wrong.

**Comment by estouneide** [comment]
Thanks very much for your response, but is not an older version. I checked a few times after you reply. All datapacks are enabled and working, except the ancient debris. Anyway, I've already lost my mind trying to resolve that, I dont wanna play anymore because os this. Thanks again for your time and patience
