### ISSUE TITLE
No me queda claro

### ISSUE THREAD

**Issue by ElTaNa88** [jsorrell/CarpetSkyAdditions#120]
Acabo de conseguir los primeros corales, y no entiendo que queréis decir con que flulla el agua del coral muerto para que genere arena. El coral es un bloque sólido no se le puede meter agua para que fluya de el... Y rodeándolo de corrientes no hace nada. Me podéis explicar cómo está adaptado esto?

**Comment by ElTaNa88** [comment]
En la wiki de Minecraft, específica que los corales pueden aparecer usando polvo de hueso en arena, en un bioma de océano cálido, pero ponte y búscalo. El problema aquí es que el mercader te vende bloques de coral y no el coral en si, hay alguna forma que se me esté escapando de convertir los bloques en plantas de coral?

**Comment by jsorrell** [comment]
The dead coral needs to be waterlogged and the water needs to flow out the side. This video shows how it is done: https://youtu.be/SI0x0sH1h-A?list=PLnC1rWWvOq51mTk75cMY8LENgR9FHWcyl&t=487

**Comment by ElTaNa88** [comment]
Lo que yo no entiendo es, ¿por qué se explica que se le compra al mercader? Este solo te vende bloques y está claro que necesitas la planta de coral no el bloque. Yo me imaginaba que sería así, pero no especificais que sea la planta. Acaso también, tiene la posibilidad de vender la planta?

**Comment by ElTaNa88** [comment]
![IMG_20230609_172239](https://github.com/jsorrell/CarpetSkyAdditions/assets/135920810/fb72775a-4344-4af7-8395-f0ffbf06561b)
Conseguido, como una imagen vale más que mil palabras, aquí dejo una de como se debe hacer. Lo único difícil fue encontrar el bioma, me llevo bastante tiempo. =)
