### ISSUE TITLE
Puesto de saqueadores

### ISSUE THREAD

**Issue by ElTaNa88** [jsorrell/CarpetSkyAdditions#121]
Alguien me puede decir, como se muestra en F3 que estoy en un puesto de saqueadores? He mirado por internet pero no parece que se muestre. En este mundo vacío, sin estructuras, como puedo encontrarlo? Llevo horas AFK esperando que me aparezcan pero nada, y ya lo único que se me ocurre es buscar un puesto de saqueadores. Si no hay forma, una opción que se podría añadir es que a un aldeano con profesión de cartógrafo te venda mapas con su localización, como lo hace con templos y la mansión.

**Comment by ElTaNa88** [comment]
Alguien que me pueda ayudar? Me hice también una plataforma de 96 de diámetro, que se supone que es el rango perfecto para que aparezca entre otras cosas el mercader y ni con esas y ni hablar de los saqueadores, la verdad es que se me quitan las ganas de seguir, estando tan cerca del nether.

**Comment by jsorrell** [comment]
You can't find a Pillager Outpost with the f3 screen. I encourage you to use the Minihud mod to show the structure outlines or to create a Default generation world with the same seed and finding the Outpost bounding boxes that way. You can use https://www.chunkbase.com/apps/pillager-outpost-finder to find the approximate location of the outpost. You could also try to get a pillager patrol to spawn but it's probably faster to find the outpost.

**Comment by ElTaNa88** [comment]
Thank you very much for the reply. I'll let you know if I managed to find it.

**Comment by ElTaNa88** [comment]
I used the page that you gave me, I had no idea it existed and I finally got it. locate the outpost and summon the raid they already gave me 3 lava buckets. Now to repeat the process until I get enough for a portal ☺️ thank you very much.
