### ISSUE TITLE
Error on creating or finding island #44

### ISSUE THREAD

**Issue by domischa** [jsorrell/CarpetSkyAdditions#125]
https://github.com/jsorrell/CarpetSkyAdditions/blob/69a46a8f4a832248227c67fb41599046da149a9b/src/main/java/com/jsorrell/carpetskyadditions/commands/SkyIslandCommand.java#L199

should be `return ISLAND_CHUNKS.get(ORDERING[i - 1]-1);`

**Comment by jsorrell** [comment]
Yeah, looks like it'll crash after 44 new islands or so. I was going back and forth between 1 and 0 indexing and must've failed. I'll probably just change 64 to 0 in ORDERING to preserve current island numbers, even if the island priority isn't perfect.
