### ISSUE TITLE
"Get Down" Advancement Glitch

### ISSUE THREAD

**Issue by BESTBATTLER8** [jsorrell/CarpetSkyAdditions#126]
Get Down Advancement Activated for me at y-level -54
![2023-06-23_18 55 50](https://github.com/jsorrell/CarpetSkyAdditions/assets/99767401/0daab9ef-ef5b-4619-991e-50ebc4714de4)

**Comment by jsorrell** [comment]
Is that wrong? It's set to go off at -54 b/c that's close enough to the bottom.
