### ISSUE TITLE
What is "Maximally Protected"???

### ISSUE THREAD

**Issue by ysysj1234** [jsorrell/CarpetSkyAdditions#134]
![image](https://github.com/jsorrell/CarpetSkyAdditions/assets/123240644/3ee03dc4-5243-4f8a-8f2e-013963f27e8c)

**Comment by jsorrell** [comment]
Wearing full Protection 4 Netherite Armor and affected by Resistance 4 (turtle master potion). The maximum amount of resistance you can get in survival.

**Comment by ysysj1234** [comment]
> Wearing full Protection 4 Netherite Armor and affected by Resistance 4 (turtle master potion). The maximum amount of resistance you can get in survival.

and What is "Thou"? Is it "You"?
![image](https://github.com/jsorrell/CarpetSkyAdditions/assets/123240644/d7d7328a-5fde-4354-b136-72d77e5ed6c4)

**Comment by jsorrell** [comment]
Yes. These titles are trying to be clever with wordplay, but don't they translate well.
The translations for advancements don't have to be exact translations. Just try to think of something clever or funny etc based on what the advancement requires.
