### ISSUE TITLE
How to do this?

### ISSUE THREAD

**Issue by ysysj1234** [jsorrell/CarpetSkyAdditions#135]
![image](https://github.com/jsorrell/CarpetSkyAdditions/assets/123240644/67028e67-421a-43d8-a4bf-3859645e0261)

**Comment by ysysj1234** [comment]
and this 
![image](https://github.com/jsorrell/CarpetSkyAdditions/assets/123240644/07ded449-de90-4828-88ff-506c77a99763)

**Comment by jsorrell** [comment]
First is just ride a camel (that a wandering trader spawns upon).

Second is described here: https://github.com/jsorrell/CarpetSkyAdditions/blob/main/docs/en_us/datapack.md#way-of-the-ancients

**Comment by ysysj1234** [comment]
> First is just ride a camel (that a wandering trader spawns upon).
> 
> Second is described here: https://github.com/jsorrell/CarpetSkyAdditions/blob/main/docs/en_us/datapack.md#way-of-the-ancients

How to "sacrifice"?

**Comment by jsorrell** [comment]
Kill

**Comment by ysysj1234** [comment]
> Kill

Thx, and I have completed all translations of SkyBlock datapack and mod at CrowdIn

**Comment by ysysj1234** [comment]
> Kill

Thx, and I have completed all Chinese translations of SkyBlock datapack and mod at CrowdIn

**Comment by ysysj1234** [comment]
> Kill
Thx, and I have completed all Simplified Chinese translations of SkyBlock datapack and mod at CrowdIn

**Comment by ysysj1234** [comment]
Thx, and I have completed all Simplified Chinese translations of SkyBlock datapack and mod at CrowdIn
Can you add them into v4.2.0?

**Comment by jsorrell** [comment]
Thanks.
4.2.0? If you want translations update for an old release, you'll have to use a resource pack with the translations.
This one should do it for everything but the /carpetskyadditions commands.
Unfortunately, translations for the carpet commands are done server side by the Carpet Mod so those need an updated mod.

[carpetskyadditions-translations.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/12298028/carpetskyadditions-translations.zip)
