### ISSUE TITLE
I want a bucket of water!!!

### ISSUE THREAD

**Issue by winingYang** [jsorrell/CarpetSkyAdditions#138]
I have prepared two cauldrons and waited for about 30 days (game time) at the same time, but I still haven't received a bucket of water!!!, in fact I also turned on cheat mode and used '/weather many times rain' command, also to no avail.

One more thing, I am also a programmer, is there anything that needs to be improved in this warehouse, maybe I can help optimize the code repository.

**Comment by jsorrell** [comment]
Cauldrons fill very slowly in Java edition. This is a purely vanilla feature, so all I can do is offer advice. Unfortunately, the only real way to speed it up is to make more cauldrons. Iron doesn't take *that* long with a decent mob farm. Only 3 combined water layer are needed between all cauldrons for infinite water (using bottles to transfer). 30 days (with extra rain) sounds like you might just be unlucky. Weather ticks are different from random ticks, so the random tick speed doesn't affect them. Just make sure you're in chunk tick (random tick) range and they are getting rained on and they'll fill eventually.

Also, thanks for the offer, but I don't think it's needed right now.

**Comment by winingYang** [comment]
all right, thank you.
