### ISSUE TITLE
Re-enable vanilla end generation

### ISSUE THREAD

**Issue by flysand7** [jsorrell/CarpetSkyAdditions#140]
Me and couple of my friends wanted to play Jokeypokey's one block series using CarpetSkyAddition. These series rely on a glitched snapshot of minecraft to obtain end portal frames, ender eyes and obsidian which is what you start with.

The first step in that progression is to enter the end, fight the dragon and obtain silk touch pick from an end city.

Though that would be impossible with carpetsky, as it can't spawn structures in the end. It would be helpful if carpetsky had an option to re-enable end city generation.

**Comment by jsorrell** [comment]
That would be simple to do with a datapack. The empty world gen is just a custom world generator and with world presets (https://minecraft.fandom.com/wiki/World_preset) you can select the generator per dimension.

This one should essentially do what you want. Just enable the datapack in the world generation screen and set the world type to `generator.carpetskyadditions.skyblock-vanilla-end`. Or set the world type to `carpetskyadditions:\skyblock-vanilla-end` in `server.properties`. Make sure to disable any unwanted properties with the `/carpetskyadditions` command upon loading.

[vanilla-end.zip](https://github.com/jsorrell/CarpetSkyAdditions/files/12491651/vanilla-end.zip)

**Comment by jsorrell** [comment]
If you want empty + end cities, that is currently not possible, but maybe I'll add that option in the future.

**Comment by flysand7** [comment]
Thanks, I guess this closes the issue!
