### ISSUE TITLE
About Chinese document

### ISSUE THREAD

**Issue by mengdiao** [jsorrell/CarpetSkyAdditions#43]
将安山岩放入高卢烧制获得凝灰岩

这句的错字

**Comment by YipKei** [comment]
> 将安山岩放入高卢烧制获得凝灰岩
> 
> 这句的错字

你可以直接将正确的文本也写出来，这样作者可以直接修改对应文本，就不用再去开个pr了。

The correct text is `将安山岩放入高炉烧制获得凝灰岩` in `/doc/zh_cn/datapack_cn.md` line 50
