### ISSUE TITLE
Server version update

### ISSUE THREAD

**Issue by Coffee-kitten** [jsorrell/CarpetSkyAdditions#45]
Hello, can you tell me how to update the server version 1.17 to the latest version 1.19
And precautions

**Comment by jsorrell** [comment]
1. Backup your world folder.
2. Update to the latest fabric server jar from https://fabricmc.net/use/server/.
3. Download the latest version of this mod, carpet, and fabric api and replace the older versions in your mods folder.
4. Delete the `skyblock-...` datapack in the datapacks folder
5. Rename `skyblock.conf` to `carpetskyadditions.conf` and replace the text in it with the settings list below.
6. Start the world.
7. Enable the new datapack with `/datapack enable "carpetskyadditions/skyblock"`.

Default settings for 4.1.0 are:
```
tallFlowersFromWanderingTrader true
lightningElectrifiesVines true
renewableBuddingAmethysts true
gatewaysSpawnChorus true
renewableHeartsOfTheSea true
renewableDragonHeads true
shulkerSpawnsOnDragonKill true
renewableDiamonds true
rammingWart true
foxesSpawnWithSweetBerriesChance 0.2
poisonousPotatoesConvertSpiders true
saplingsDieOnSand true
renewableEchoShards true
renewableAllays true
coralErosion true
hugeMushroomsSpreadMycelium true
renewableNetherrack true
renewableDeepslate true
renewableSwiftSneak true
```

The advancements from this mod will be reset, but most of them are different between 1.17 and 1.19 anyway.

**Comment by Coffee-kitten** [comment]
thanks reply
