### ISSUE TITLE
New world in Aternos server

### ISSUE THREAD

**Issue by Kolya85** [jsorrell/CarpetSkyAdditions#49]
Hello,
I have tried to create a world on the Aternos server so I can play Skyblock with my friends, but it has not been possible.
Aternos has the 'Carpet Sky Additions' mod available but trying to start it throws the error:
- Mod 'Carpet Sky Additions' (carpetskyadditions) 1.19-4.1.0 requires any version of carpet, which is missing!

Aternos does not allow the installation of the Carpet mod, so I don't know how to create a Skyblock server

You can help?

**Comment by jsorrell** [comment]
This mod is designed as a Carpet extension, so Carpet is required. I might look into making a fork that doesn't require Carpet and instead uses its own settings system (this shouldn't be too hard to do). However, to be allowed by Aternos it would still need 1000 downloads I think. Unfortunately, I don't think Aternos will be supported in the near future.

**Comment by Kolya85** [comment]
Thanks for your answer.
I already assumed that this mod was an extension of Carpet and that Aternos does not allow Carpet is precisely the problem.
If you made that fork, as you say, it would be difficult for Aternos to accept it, even so, I think the community would appreciate it.
I leave it in your hands and thanks for a great job with this mod.

**Comment by Mrloic23** [comment]
> This mod is designed as a Carpet extension, so Carpet is required. I might look into making a fork that doesn't require Carpet and instead uses its own settings system (this shouldn't be too hard to do). However, to be allowed by Aternos it would still need 1000 downloads I think. Unfortunately, I don't think Aternos will be supported in the near future.

also Aternos won't accept it if you develop it "specifically for aternos" (carpet without fake player had that exact issue)

**Comment by jsorrell** [comment]
@Mrloic23 
> also Aternos won't accept it if you develop it "specifically for aternos" (carpet without fake player had that exact issue)

Yeah. It wouldn't be specifically developed for Aternos as there are many other uses, but they might see it that way.

**Comment by fudge-afk** [comment]
Would you consider developing a fork for QuickCarpet? 
It's allowed on Aternos, and has the renewable piglin brute and renewable elder guardian settings being used in the skyblock world from the Carpet mod. That would probably assuage concerns that it is tailored specially for Aternos, as it would be beneficial to any server seeking certain Carpet features like the server-side autoclicker or the renewables  settings but not the bot creation capability.
