### ISSUE TITLE
Advancements not showing up

### ISSUE THREAD

**Issue by CounterSync03** [jsorrell/CarpetSkyAdditions#50]
The advancements page says "There doesn't seem to be anything here..."

Tried installing through Curseforge, and also tried installing through Fabric and didn't get any different results.

I am new to GitHub so could be an error on my end but don't see anywhere that could cause this problem.

Thanks :)

**Comment by jsorrell** [comment]
Sounds like you're not enabling the datapack. You can do this in the create world screen by clicking on Data Packs then clicking on "carpetskyadditions/skyblock" on the left. You can also enable it in an existing world (with cheats enabled) with `/datapack enable "carpetskyadditions/skyblock"`.
