### ISSUE TITLE
No mobs are spawning in 4.1.1?

### ISSUE THREAD

**Issue by istvanmate** [jsorrell/CarpetSkyAdditions#51]
While I had mobs spawning in 4.1.0, I got no spawns in 4.1.1

**Comment by jsorrell** [comment]
I just tested both monster and creature spawning in 4.1.1 for both singleplayer and server worlds and it works fine for me. Maybe try testing in a creative world or using carpet's `spawn list` command to check the spawning requirements?

**Comment by istvanmate** [comment]
I did enlarge the spawning in creative and got mobs. Maybe I was impatient. Anyway, it works.
