### ISSUE TITLE
carpetskyadditions/skyblock_acacia not generating acacia start island

### ISSUE THREAD

**Issue by ravenge-au** [jsorrell/CarpetSkyAdditions#54]
Versions:
carpetskyadditions-1.19.2-4.1.2.jar
fabric-api-0.62.0+1.19.2.jar
fabric-carpet-1.19.1-1.4.83+v220727.jar

I followed the instructions:

> **Multiplayer**
> The mod is only required server-side.
> 
> Create a [Fabric Server](https://fabricmc.net/use/server/)
> Download [fabric-api](https://www.curseforge.com/minecraft/mc-mods/fabric-api/files)
> Download [fabric-carpet](https://www.curseforge.com/minecraft/mc-mods/carpet/files)
> Download [Carpet Sky Additions](https://github.com/jsorrell/CarpetSkyAdditions/releases)
> Start the server to generate a template server.properties file
> Shut down the server
> Delete world folder the server created
> Place fabric-carpet, fabric-api, and SkyBlock into <server-directory>/mods/
> Open server.properties
> Change level-type=minecraft\:normal to level-type=carpetskyadditions\:skyblock
> Start the server
> Run datapack enable "carpetskyadditions/skyblock" to enable the datapack

Also ran:
datapack enable "carpetskyadditions/skyblock_acacia"

Then player logs in for the first time. 

Starter Island is still Oak Tree. Did I miss a step?

Much appreciated.

**Comment by Tvitser** [comment]
You need to change level-type=carpetskyadditions:skyblock to level-type=carpetskyadditions:skyblock_acacia to spawn acacia tree instead oak

**Comment by jsorrell** [comment]
The problem is that the acacia datapack must be enabled before the world generates which isn't really easy to do on a server world.

I think the best option for acacia gen on a server is to generate the world in single player then copy the save to your server renaming it to "world".

I will update the docs to try to reflect this.

**Comment by jsorrell** [comment]
You could also download the datapack [here](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fjsorrell%2FCarpetSkyAdditions%2Ftree%2F1.19%2Falternate-spawn-datapacks%2Fskyblock_acacia) and put it in your datapacks folder. Then delete the world folder and restart the server. This might be eaaier.

**Comment by ravenge-au** [comment]
> The problem is that the acacia datapack must be enabled before the world generates which isn't really easy to do on a server world.

I thought this may have been the case watching the server log as the mod spun up.  Using the provided datapack was easiest for me as I have created my server in a docker container. (although I did spawn on top of the tree lol).

Thanks for the quick response!
