### ISSUE TITLE
carpetskyadditions/skyblock_acacia doesn't include skyblock advancements

### ISSUE THREAD

**Issue by Tvitser** [jsorrell/CarpetSkyAdditions#55]
carpetskyadditions/skyblock gives you advancements custom advancements (https://i.imgur.com/xOpt4gB.png), but carpetskyadditions/skyblock_acacia doesnt (https://i.imgur.com/FNacT14.png)

**Comment by jsorrell** [comment]
You need to enable both of the datapacks: "skyblock" and "skyblock_acacia"
