### ISSUE TITLE
Can't tame horse

### ISSUE THREAD

**Issue by Uffi92** [jsorrell/CarpetSkyAdditions#57]
When trying to tame a horse the horse does not buck. -> I can sit on it forever without taming it. This issue only occurs in my skyblock worlds. (in creative and survival)

**Comment by jsorrell** [comment]
I just tested in a new skyblock world and I can't reproduce. This mod doesn't change anything to do with horses, so it's weird to think this mod is doing it. Have you changed any default settings?

**Comment by Uffi92** [comment]
Sorry, I just did some more testing. The issue was, that the horse did stand on a halfslap(I build nearly everything out of them in my survival and testworld). So, nothing wrong with the mod. Thank you for the fast response and the great mod.

BR Alex
