### ISSUE TITLE
Villagers wont breed

### ISSUE THREAD

**Issue by Chrisco84** [jsorrell/CarpetSkyAdditions#60]
I have tried breeding villagers with both carrots and potatoes and still not having any luck.

**Comment by Tvitser** [comment]
Do u have beds near villagers? Are there more than 2 blocks above beds?

**Comment by Tvitser** [comment]
If you can, take screenshot of your breeder

**Comment by Chrisco84** [comment]
I will get a screen shot tomorrow after work. It’s currently 11:40pm here in Australia. 

Yes there are beds near the villagers and 2 blocks above the beds.

The villagers just seem to look at the carrots on the ground without picking them up.

**Comment by jsorrell** [comment]
I tested breeding in a new empty world and it works fine. As long as the villagers have empty slots in their inventory and the carrots and potatoes are close enough, they should pick them up. It's possible their inventory is filled with seeds or wheat, which would mean they won't breed and won't pick things up.

**Comment by Chrisco84** [comment]
Ok thanks for the update. I will sus it out later today.
