### ISSUE TITLE
 Failed to parse level-type carpetskyadditions:skyblock

### ISSUE THREAD

**Issue by 6rube** [jsorrell/CarpetSkyAdditions#66]
I try to start the server but it cant parse the option for some reason.

16.10 20:43:39 [Server] main/WARN Failed to parse level-type carpetskyadditions:skyblock, defaulting to minecraft:normal

**Comment by jsorrell** [comment]
Are you sure the mod is loading? It should list all mods being loaded at the beginning of the log at the INFO level.
