### ISSUE TITLE
No Passive Mob or Wandering Trader is Spawning

### ISSUE THREAD

**Issue by RealDapi** [jsorrell/CarpetSkyAdditions#68]
I tried everything but nothing seems to work

**Comment by jsorrell** [comment]
Pretty sure this isn't an issue with this mod. Make sure your creature mob cap isn't full and your spawn area is in a good biome. Passive mobs try to spawn 400x less often than hostile mobs and their mobcap is 7 times smaller, so getting them to spawn needs knowledge of their spawn mechanics. Maybe test in a creative world.

**Comment by RealDapi** [comment]
I tried it in multiple Creative Worlds, multiple altitudes and bioms. I don't get it to work in the skyblock worlds

**Comment by jsorrell** [comment]
Hmm. I just created a new world in both 1.19-4.1.3 and 1.19.2-4.1.3, used `/fill` to create a grass platform and cows, sheep, chickens etc spawned immediately. What version of Minecraft and the mod are you on and how are you testing?

**Comment by RealDapi** [comment]
Well, I'm testing the same way with version 19.2-4.1.3 and the /fill command. But I now tested with just carpet mod and without the Add-on and it's not working either so it must be something with carpet. Ofc I tested it without any mods too and it worked...

**Comment by RealDapi** [comment]
After installing a older version of carpet it worked flawless.

**Comment by jsorrell** [comment]
Maybe submit an issue to the Carpet mod then. Thanks for reporting.
