### ISSUE TITLE
No lava bucket!

### ISSUE THREAD

**Issue by illimay** [jsorrell/CarpetSkyAdditions#71]
I've been waiting around villagers with jobs (the jobs they could acquire without workstations that require cobblestone), and wandering traders, but I'm not getting anything.. 
Could this be a bug?

**Comment by offbeat-stuff** [comment]
you should read up about wandering trader spawning

**Comment by offbeat-stuff** [comment]
a wandering spawn on average in around 4 hours in a 96 by 96 area around the player and only spawns on the top block so

**Comment by Hangsna** [comment]
Do you get other gifts?
The documentation says "Once you have the Hero of the Village effect, stand by a Toolsmith and they may gift you a Lava Bucket." So it have to be a toolsmith (needs smithing table) and you have to have Hero of the Village (so defeat a raid first).
To get it from a wandering trader you need to enable (its off by default) it by doing: /carpetskyadditions setDefault lavaFromWanderingTrader true

**Comment by libera-git** [comment]
have received thousands of tools but no lava bucket. Hero I or V no difference

**Comment by jsorrell** [comment]
Just tested this and received a lava bucket as the 2nd gift. Make sure you have the datapack enabled (if using the acacia start, you need both datapacks) as this is a feature of the datapack. If you see the custom advancements you should be good. The lava bucket gift has a weight of 2, so it's a 1/21 chance with toolsmiths and armorers and a 1/16 chance with weaponsmiths.

**Comment by libera-git** [comment]
Apparently I started my world without the datapack. I tried starting a new
world and did load the datapack - saw the achievement new tree but for some
reason the two special dirt blocks are not generating. I'm new to the whole
mod thing and it's a bit mystifying.
