### ISSUE TITLE
Why it does not work?

### ISSUE THREAD

**Issue by mouel466** [jsorrell/CarpetSkyAdditions#85]
It used to work a while ago before the update but now it does not.

When I run Minecraft with this version latest fabric 1.19.3 it throws this error

`Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cloth-config2, any version.
Unmet dependency listing:
	 - Mod 'Carpet Sky Additions' (carpetskyadditions) 1.19.3-4.2.0 requires any version of cloth-config2, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
`

I do have cloth-config2 in the mod files
![image](https://user-images.githubusercontent.com/42760518/213863954-fecaa5aa-bbac-4352-83ae-99de8ade9d9a.png)

And when I try to use Forge to run it, the game opens but the mod does not show up at all, and there is no new word type added and even the data packs don't show up.

**Comment by mouel466** [comment]
Just realized that I downloaded cloth-config for forge instead of fabric. It working now :)

**Comment by eliannelavoie** [comment]
Thanks! I do think it might be worth it to mention to make sure to take the right version in the advanced installation instructions: it's a really easy mistake to make, since clicking the main "Download" button on the linked page will download the wrong version.

**Comment by jsorrell** [comment]
Ok. I'll change the link to https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all?filter-game-version=2020709689%3A7499 which should filter for only Fabric versions.
