### ISSUE TITLE
Red and Blue Nylium Blocks not spawning

### ISSUE THREAD

**Issue by Braaivleis** [jsorrell/CarpetSkyAdditions#86]
Hi, so i downloaded and followed the instructions, starter island spawns but is missing th blue and red nylium blocks. Did i skip something by accident because i redownloaded and installed 2 more times after and still the same.

**Comment by jsorrell** [comment]
Nylium doesn't generate on the island anymore. You get it through nether portals.

**Comment by Braaivleis** [comment]
Thank you, i thought i broke something, anyway awesome data pack man! Love it
