### ISSUE TITLE
World creation: Data pack validation failed!

### ISSUE THREAD

**Issue by sraL2711** [jsorrell/CarpetSkyAdditions#90]
Heyho,
im trying to set up my own skyblock wolrd the first time. I checked if the data packs might have the wrong version (currently carpetskyadditions-1.19.3-4.2.0; cloth-config-9.0.94-fabric; fabric-carpet-1.19.3-1.4.96+v230201) and im playing on 1.19.3 of course. AS soon as I switch out the default Datapack with CarpetskyAddtitions and click on DONE it says Dara pack validation failed!
What am I supposed to do now? Or is it the wrong way to set this up?

**Comment by jsorrell** [comment]
The Default datapack is supposed to stay enabled. Just make sure the SkyBlock datapack is higher in the list and it will override the defaults.
