### ISSUE TITLE
Quilt Support?

### ISSUE THREAD

**Issue by otter501** [jsorrell/CarpetSkyAdditions#94]
I know that this mod is not meant to be quilt compatible, It was just be nice to add quilt support

**Comment by jsorrell** [comment]
I don't have experience with Quilt, but I just tried it with the Quilt loader and it seems to work just as well as Fabric. Have you had compatibility issues?

**Comment by otter501** [comment]
I have now realized it was just a conflict with another mod

**Comment by otter501** [comment]
It pretty much is having issues with almost every other mod, probably just something odd to do with quilt

**Comment by jsorrell** [comment]
Can I have some examples? I'll look into it.

**Comment by otter501** [comment]
https://mclo.gs/uIIMzrU
I hope this will help

**Comment by otter501** [comment]
so it appears to be an issue with the [Quilt Standard Libraries](https://github.com/QuiltMC/quilt-standard-libraries), could you check if you mod uses any of the unsupported features?

**Comment by jsorrell** [comment]
The log helped thanks.
Fixed in 4.3.1

**Comment by otter501** [comment]
thank you
