### ISSUE TITLE
Enabling mod features on an existing world

### ISSUE THREAD

**Issue by monke665** [jsorrell/CarpetSkyAdditions#95]
I want to have the mod features (like coral sand farming and netherrack generation) in my existing protosky world. It seems like simply adding the mod into your mod folder doesn't do it.

**Comment by jsorrell** [comment]
You have to enable the features you want specifically. Use the `/carpetskyadditions` command and it will list each setting. The datapack is enabled all at once using the `datapack` command if you want to use that.

**Comment by monke665** [comment]
I don't want to enable cheats. Can you make the external datapack automatically enable these features?

**Comment by jsorrell** [comment]
If you just want the default settings (as of 1.19.3-4.2.0), you can just put these two files in your world folder.


 `carpet.conf`
```
renewableSponges true
piglinsSpawningInBastions true
```
`carpetskyadditions.conf`
```
tallFlowersFromWanderingTrader true
lightningElectrifiesVines true
renewableBuddingAmethysts true
gatewaysSpawnChorus true
renewableHeartsOfTheSea true
renewableDragonHeads true
shulkerSpawnsOnDragonKill true
renewableDiamonds true
rammingWart true
foxesSpawnWithSweetBerriesChance 0.2
poisonousPotatoesConvertSpiders true
saplingsDieOnSand true
renewableEchoShards true
allayableVexes true
coralErosion true
hugeMushroomsSpreadMycelium true
renewableNetherrack true
renewableDeepslate true
renewableSwiftSneak true
```

**Comment by monke665** [comment]
Thank you so much.
