### ISSUE TITLE
No Lava Bucket gifting on server install.

### ISSUE THREAD

**Issue by jamesrgallen** [jsorrell/CarpetSkyAdditions#99]
Hopin you can help, I have a skyblock fabric server and have gotten to the stage where we are trying to get Lava buckets from the hero of the village. We have recieved no joke around 200 stone tools and not a single laval bucket so pretty sure its somehow broken. Please advice where I messed up!

**Comment by jsorrell** [comment]
The lava bucket gifting is part of the datapack, so make sure you have the built-in datapack enabled.
